"""empty message

Revision ID: 76589c134329
Revises: 46c641a812ac
Create Date: 2020-10-16 00:59:48.293237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76589c134329'
down_revision = '46c641a812ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'shows', ['venue_id', 'artist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='unique')
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
